// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.grpc;

public final class Reservation {
  private Reservation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReservationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.ReservationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string customer_name = 1;</code>
     * @return The customerName.
     */
    java.lang.String getCustomerName();
    /**
     * <code>string customer_name = 1;</code>
     * @return The bytes for customerName.
     */
    com.google.protobuf.ByteString
        getCustomerNameBytes();

    /**
     * <code>string room_type = 2;</code>
     * @return The roomType.
     */
    java.lang.String getRoomType();
    /**
     * <code>string room_type = 2;</code>
     * @return The bytes for roomType.
     */
    com.google.protobuf.ByteString
        getRoomTypeBytes();

    /**
     * <code>int32 nights = 3;</code>
     * @return The nights.
     */
    int getNights();
  }
  /**
   * Protobuf type {@code com.grpc.ReservationRequest}
   */
  public  static final class ReservationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.ReservationRequest)
      ReservationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReservationRequest.newBuilder() to construct.
    private ReservationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReservationRequest() {
      customerName_ = "";
      roomType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReservationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReservationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              customerName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              roomType_ = s;
              break;
            }
            case 24: {

              nights_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.Reservation.internal_static_com_grpc_ReservationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.Reservation.internal_static_com_grpc_ReservationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.Reservation.ReservationRequest.class, com.grpc.Reservation.ReservationRequest.Builder.class);
    }

    public static final int CUSTOMER_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object customerName_;
    /**
     * <code>string customer_name = 1;</code>
     * @return The customerName.
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      }
    }
    /**
     * <code>string customer_name = 1;</code>
     * @return The bytes for customerName.
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOM_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object roomType_;
    /**
     * <code>string room_type = 2;</code>
     * @return The roomType.
     */
    public java.lang.String getRoomType() {
      java.lang.Object ref = roomType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomType_ = s;
        return s;
      }
    }
    /**
     * <code>string room_type = 2;</code>
     * @return The bytes for roomType.
     */
    public com.google.protobuf.ByteString
        getRoomTypeBytes() {
      java.lang.Object ref = roomType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NIGHTS_FIELD_NUMBER = 3;
    private int nights_;
    /**
     * <code>int32 nights = 3;</code>
     * @return The nights.
     */
    public int getNights() {
      return nights_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCustomerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, customerName_);
      }
      if (!getRoomTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomType_);
      }
      if (nights_ != 0) {
        output.writeInt32(3, nights_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCustomerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, customerName_);
      }
      if (!getRoomTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomType_);
      }
      if (nights_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, nights_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.Reservation.ReservationRequest)) {
        return super.equals(obj);
      }
      com.grpc.Reservation.ReservationRequest other = (com.grpc.Reservation.ReservationRequest) obj;

      if (!getCustomerName()
          .equals(other.getCustomerName())) return false;
      if (!getRoomType()
          .equals(other.getRoomType())) return false;
      if (getNights()
          != other.getNights()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CUSTOMER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerName().hashCode();
      hash = (37 * hash) + ROOM_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRoomType().hashCode();
      hash = (37 * hash) + NIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + getNights();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.Reservation.ReservationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.Reservation.ReservationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.Reservation.ReservationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.Reservation.ReservationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.ReservationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.ReservationRequest)
        com.grpc.Reservation.ReservationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.Reservation.internal_static_com_grpc_ReservationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.Reservation.internal_static_com_grpc_ReservationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.Reservation.ReservationRequest.class, com.grpc.Reservation.ReservationRequest.Builder.class);
      }

      // Construct using com.grpc.Reservation.ReservationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        customerName_ = "";

        roomType_ = "";

        nights_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.Reservation.internal_static_com_grpc_ReservationRequest_descriptor;
      }

      @java.lang.Override
      public com.grpc.Reservation.ReservationRequest getDefaultInstanceForType() {
        return com.grpc.Reservation.ReservationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.Reservation.ReservationRequest build() {
        com.grpc.Reservation.ReservationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.Reservation.ReservationRequest buildPartial() {
        com.grpc.Reservation.ReservationRequest result = new com.grpc.Reservation.ReservationRequest(this);
        result.customerName_ = customerName_;
        result.roomType_ = roomType_;
        result.nights_ = nights_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.Reservation.ReservationRequest) {
          return mergeFrom((com.grpc.Reservation.ReservationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.Reservation.ReservationRequest other) {
        if (other == com.grpc.Reservation.ReservationRequest.getDefaultInstance()) return this;
        if (!other.getCustomerName().isEmpty()) {
          customerName_ = other.customerName_;
          onChanged();
        }
        if (!other.getRoomType().isEmpty()) {
          roomType_ = other.roomType_;
          onChanged();
        }
        if (other.getNights() != 0) {
          setNights(other.getNights());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.Reservation.ReservationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.Reservation.ReservationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object customerName_ = "";
      /**
       * <code>string customer_name = 1;</code>
       * @return The customerName.
       */
      public java.lang.String getCustomerName() {
        java.lang.Object ref = customerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customer_name = 1;</code>
       * @return The bytes for customerName.
       */
      public com.google.protobuf.ByteString
          getCustomerNameBytes() {
        java.lang.Object ref = customerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customer_name = 1;</code>
       * @param value The customerName to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string customer_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerName() {
        
        customerName_ = getDefaultInstance().getCustomerName();
        onChanged();
        return this;
      }
      /**
       * <code>string customer_name = 1;</code>
       * @param value The bytes for customerName to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object roomType_ = "";
      /**
       * <code>string room_type = 2;</code>
       * @return The roomType.
       */
      public java.lang.String getRoomType() {
        java.lang.Object ref = roomType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string room_type = 2;</code>
       * @return The bytes for roomType.
       */
      public com.google.protobuf.ByteString
          getRoomTypeBytes() {
        java.lang.Object ref = roomType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string room_type = 2;</code>
       * @param value The roomType to set.
       * @return This builder for chaining.
       */
      public Builder setRoomType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string room_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomType() {
        
        roomType_ = getDefaultInstance().getRoomType();
        onChanged();
        return this;
      }
      /**
       * <code>string room_type = 2;</code>
       * @param value The bytes for roomType to set.
       * @return This builder for chaining.
       */
      public Builder setRoomTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomType_ = value;
        onChanged();
        return this;
      }

      private int nights_ ;
      /**
       * <code>int32 nights = 3;</code>
       * @return The nights.
       */
      public int getNights() {
        return nights_;
      }
      /**
       * <code>int32 nights = 3;</code>
       * @param value The nights to set.
       * @return This builder for chaining.
       */
      public Builder setNights(int value) {
        
        nights_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nights = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNights() {
        
        nights_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.ReservationRequest)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.ReservationRequest)
    private static final com.grpc.Reservation.ReservationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.Reservation.ReservationRequest();
    }

    public static com.grpc.Reservation.ReservationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReservationRequest>
        PARSER = new com.google.protobuf.AbstractParser<ReservationRequest>() {
      @java.lang.Override
      public ReservationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReservationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReservationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReservationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.Reservation.ReservationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReservationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.ReservationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string status = 1;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string reservation_id = 2;</code>
     * @return The reservationId.
     */
    java.lang.String getReservationId();
    /**
     * <code>string reservation_id = 2;</code>
     * @return The bytes for reservationId.
     */
    com.google.protobuf.ByteString
        getReservationIdBytes();
  }
  /**
   * Protobuf type {@code com.grpc.ReservationResponse}
   */
  public  static final class ReservationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.ReservationResponse)
      ReservationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReservationResponse.newBuilder() to construct.
    private ReservationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReservationResponse() {
      status_ = "";
      reservationId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReservationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReservationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              reservationId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.Reservation.internal_static_com_grpc_ReservationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.Reservation.internal_static_com_grpc_ReservationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.Reservation.ReservationResponse.class, com.grpc.Reservation.ReservationResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 1;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESERVATION_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object reservationId_;
    /**
     * <code>string reservation_id = 2;</code>
     * @return The reservationId.
     */
    public java.lang.String getReservationId() {
      java.lang.Object ref = reservationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reservationId_ = s;
        return s;
      }
    }
    /**
     * <code>string reservation_id = 2;</code>
     * @return The bytes for reservationId.
     */
    public com.google.protobuf.ByteString
        getReservationIdBytes() {
      java.lang.Object ref = reservationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reservationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
      }
      if (!getReservationIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reservationId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
      }
      if (!getReservationIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, reservationId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.Reservation.ReservationResponse)) {
        return super.equals(obj);
      }
      com.grpc.Reservation.ReservationResponse other = (com.grpc.Reservation.ReservationResponse) obj;

      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getReservationId()
          .equals(other.getReservationId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + RESERVATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getReservationId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.Reservation.ReservationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.Reservation.ReservationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.Reservation.ReservationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.Reservation.ReservationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.ReservationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.ReservationResponse)
        com.grpc.Reservation.ReservationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.Reservation.internal_static_com_grpc_ReservationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.Reservation.internal_static_com_grpc_ReservationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.Reservation.ReservationResponse.class, com.grpc.Reservation.ReservationResponse.Builder.class);
      }

      // Construct using com.grpc.Reservation.ReservationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = "";

        reservationId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.Reservation.internal_static_com_grpc_ReservationResponse_descriptor;
      }

      @java.lang.Override
      public com.grpc.Reservation.ReservationResponse getDefaultInstanceForType() {
        return com.grpc.Reservation.ReservationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.Reservation.ReservationResponse build() {
        com.grpc.Reservation.ReservationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.Reservation.ReservationResponse buildPartial() {
        com.grpc.Reservation.ReservationResponse result = new com.grpc.Reservation.ReservationResponse(this);
        result.status_ = status_;
        result.reservationId_ = reservationId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.Reservation.ReservationResponse) {
          return mergeFrom((com.grpc.Reservation.ReservationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.Reservation.ReservationResponse other) {
        if (other == com.grpc.Reservation.ReservationResponse.getDefaultInstance()) return this;
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getReservationId().isEmpty()) {
          reservationId_ = other.reservationId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.Reservation.ReservationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.Reservation.ReservationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 1;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 1;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 1;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reservationId_ = "";
      /**
       * <code>string reservation_id = 2;</code>
       * @return The reservationId.
       */
      public java.lang.String getReservationId() {
        java.lang.Object ref = reservationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reservationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reservation_id = 2;</code>
       * @return The bytes for reservationId.
       */
      public com.google.protobuf.ByteString
          getReservationIdBytes() {
        java.lang.Object ref = reservationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reservationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reservation_id = 2;</code>
       * @param value The reservationId to set.
       * @return This builder for chaining.
       */
      public Builder setReservationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reservationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reservation_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReservationId() {
        
        reservationId_ = getDefaultInstance().getReservationId();
        onChanged();
        return this;
      }
      /**
       * <code>string reservation_id = 2;</code>
       * @param value The bytes for reservationId to set.
       * @return This builder for chaining.
       */
      public Builder setReservationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reservationId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.ReservationResponse)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.ReservationResponse)
    private static final com.grpc.Reservation.ReservationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.Reservation.ReservationResponse();
    }

    public static com.grpc.Reservation.ReservationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReservationResponse>
        PARSER = new com.google.protobuf.AbstractParser<ReservationResponse>() {
      @java.lang.Override
      public ReservationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReservationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReservationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReservationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.Reservation.ReservationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_ReservationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_ReservationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_ReservationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_ReservationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\022\010com.grpc\"N\n\022Reserva" +
      "tionRequest\022\025\n\rcustomer_name\030\001 \001(\t\022\021\n\tro" +
      "om_type\030\002 \001(\t\022\016\n\006nights\030\003 \001(\005\"=\n\023Reserva" +
      "tionResponse\022\016\n\006status\030\001 \001(\t\022\026\n\016reservat" +
      "ion_id\030\002 \001(\t2\272\001\n\027HotelReservationService" +
      "\022P\n\021CreateReservation\022\034.com.grpc.Reserva" +
      "tionRequest\032\035.com.grpc.ReservationRespon" +
      "se\022M\n\016GetReservation\022\034.com.grpc.Reservat" +
      "ionRequest\032\035.com.grpc.ReservationRespons" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_grpc_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_ReservationRequest_descriptor,
        new java.lang.String[] { "CustomerName", "RoomType", "Nights", });
    internal_static_com_grpc_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_ReservationResponse_descriptor,
        new java.lang.String[] { "Status", "ReservationId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
