// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.grpc.stubs;

public final class ReservationOuterClass {
  private ReservationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveReservationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\"g\n\013Reservation\022\n\n\002id" +
      "\030\001 \001(\t\022\024\n\014customerName\030\002 \001(\t\022\023\n\013descript" +
      "ion\030\003 \001(\t\022\017\n\007checkIn\030\004 \001(\t\022\020\n\010checkOut\030\005" +
      " \001(\t\"b\n\022ReservationRequest\022\024\n\014customerNa" +
      "me\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\017\n\007checkIn" +
      "\030\003 \001(\t\022\020\n\010checkOut\030\004 \001(\t\"\033\n\031GetAllReserv" +
      "ationsRequest\"@\n\032GetAllReservationsRespo" +
      "nse\022\"\n\014reservations\030\001 \003(\0132\014.Reservation\"" +
      "\'\n\031GetReservationByIdRequest\022\n\n\002id\030\001 \001(\t" +
      "\"?\n\032GetReservationByIdResponse\022!\n\013reserv" +
      "ation\030\001 \001(\0132\014.Reservation\"B\n\026SaveReserva" +
      "tionRequest\022(\n\013reservation\030\001 \001(\0132\023.Reser" +
      "vationRequest\"<\n\027SaveReservationResponse" +
      "\022!\n\013reservation\030\001 \001(\0132\014.Reservation2\362\001\n\022" +
      "ReservationService\022J\n\017AllReservations\022\032." +
      "GetAllReservationsRequest\032\033.GetAllReserv" +
      "ationsResponse\022J\n\017ReservationById\022\032.GetR" +
      "eservationByIdRequest\032\033.GetReservationBy" +
      "IdResponse\022D\n\017SaveReservation\022\027.SaveRese" +
      "rvationRequest\032\030.SaveReservationResponse" +
      "B\030\n\024ma.projet.grpc.stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "CustomerName", "Description", "CheckIn", "CheckOut", });
    internal_static_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationRequest_descriptor,
        new java.lang.String[] { "CustomerName", "Description", "CheckIn", "CheckOut", });
    internal_static_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAllReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_GetReservationByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetReservationByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetReservationByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_SaveReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SaveReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_SaveReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SaveReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
