// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.grpc.stubs;

public interface GetAllReservationsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllReservationsRequest)
    com.google.protobuf.MessageOrBuilder {
}
