// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.grpc.stubs;

public interface ReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customerName = 1;</code>
   * @return The customerName.
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customerName = 1;</code>
   * @return The bytes for customerName.
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string checkIn = 3;</code>
   * @return The checkIn.
   */
  java.lang.String getCheckIn();
  /**
   * <code>string checkIn = 3;</code>
   * @return The bytes for checkIn.
   */
  com.google.protobuf.ByteString
      getCheckInBytes();

  /**
   * <code>string checkOut = 4;</code>
   * @return The checkOut.
   */
  java.lang.String getCheckOut();
  /**
   * <code>string checkOut = 4;</code>
   * @return The bytes for checkOut.
   */
  com.google.protobuf.ByteString
      getCheckOutBytes();
}
